# Generated by Django 2.2.12 on 2020-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_auto_20200619_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerType', models.CharField(max_length=32, null=True)),
                ('ServiceName', models.CharField(max_length=32, null=True)),
                ('ShortName', models.CharField(max_length=32, null=True)),
                ('DeptId', models.IntegerField(null=True)),
                ('DeptName', models.CharField(max_length=32, null=True)),
                ('SubDeptId', models.IntegerField(null=True)),
                ('SubDeptName', models.CharField(max_length=32, null=True)),
                ('SerAmount', models.IntegerField(null=True)),
                ('OPDrNameinBilling', models.BooleanField(null=True)),
                ('OPReferalBilling', models.BooleanField(null=True)),
                ('OPDiscountApply', models.BooleanField(null=True)),
                ('OPEditServiceAmt', models.BooleanField(null=True)),
                ('OPEditQty', models.BooleanField(null=True)),
                ('OPToken', models.BooleanField(null=True)),
                ('IPDrNameinBilling', models.BooleanField(null=True)),
                ('IPReferalBilling', models.BooleanField(null=True)),
                ('IPDiscountApply', models.BooleanField(null=True)),
                ('IPEditServiceAmt', models.BooleanField(null=True)),
                ('IPEditQty', models.BooleanField(null=True)),
                ('IPToken', models.BooleanField(null=True)),
                ('IRDACode', models.CharField(max_length=32, null=True)),
                ('IRDAName', models.CharField(max_length=32, null=True)),
                ('Outsource', models.BooleanField(null=True)),
                ('BillingSequence', models.IntegerField(null=True)),
                ('Isactive', models.BooleanField(null=True)),
                ('AddedBY', models.CharField(max_length=32, null=True)),
                ('Addeddate', models.CharField(max_length=32, null=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discountype',
            name='password',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
