# Generated by Django 2.2.12 on 2020-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_auto_20200622_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='packagemapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackCode', models.IntegerField(null=True)),
                ('PackSerCode', models.IntegerField(null=True)),
                ('PackSerAmt', models.IntegerField(null=True)),
                ('DrCode', models.IntegerField(null=True)),
                ('Isactive', models.BooleanField(null=True)),
                ('AddedBY', models.CharField(max_length=32, null=True)),
                ('Addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
