# Generated by Django 3.0.5 on 2020-12-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_packagemapping_packcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantSlutMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time_from', models.CharField(max_length=40)),
                ('time_to', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('slot_duration', models.IntegerField(default=15)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.professional')),
            ],
        ),
    ]
