# Generated by Django 3.0.5 on 2020-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_consultantslutmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantslutmaster',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultantslutmaster',
            name='modified_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
