# Generated by Django 3.0.5 on 2020-12-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20201229_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Doctor'},
        ),
    ]
