# Generated by Django 3.0.5 on 2021-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20201231_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountype',
            name='password',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
