# Generated by Django 3.0.5 on 2021-01-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20210105_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultantSlutMaster',
            new_name='ConsultantSlotMaster',
        ),
    ]
