# Generated by Django 3.0.5 on 2020-12-22 07:10

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_billheader_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billreceipt',
            name='RecNo',
            field=models.CharField(default=transactions.models.generetRecNo, max_length=32, null=True),
        ),
    ]
