# Generated by Django 3.0.5 on 2020-12-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_packagemapping_packcode'),
        ('transactions', '0013_auto_20201222_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depertment', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(auto_now=True)),
                ('appointment_time', models.CharField(max_length=50)),
                ('appointment_reason', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.professional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.patient_registration')),
            ],
        ),
    ]
