# Generated by Django 3.0.5 on 2020-12-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_bookappointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAppointments',
        ),
    ]
