# Generated by Django 3.0.5 on 2020-12-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20201231_1136'),
        ('transactions', '0019_auto_20201224_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='DrCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.professional'),
        ),
    ]
