# Generated by Django 3.0.5 on 2020-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20201231_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billreceipt',
            name='CardTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='billreceipt',
            name='OtherPaid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
