# Generated by Django 3.0.5 on 2021-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_prescriptionheader_prescriptionmedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionheader',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
