# Generated by Django 3.0.5 on 2021-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20210102_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionheader',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
