# Generated by Django 3.0.5 on 2021-01-05 05:43

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_auto_20210104_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='mrn_no',
            field=models.CharField(default=transactions.models.genaret_mrn, max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='bill_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='transactions.billheader'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='prescription_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='transactions.PrescriptionHeader'),
        ),
    ]
