# Generated by Django 3.0.5 on 2021-01-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_auto_20210105_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billheader',
            name='DiscNote',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billheader',
            name='DiscountBy',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
