# Generated by Django 3.0.5 on 2021-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_auto_20210120_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='relationType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
