# Generated by Django 3.0.5 on 2021-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_auto_20210121_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='IdentificationType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='IdentificationValue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
